version: "3.1"
services:
  db: 
    image: postgres:15.2
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=devstoredb_development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

      # D:/Belajar/studidevsecops/bootcamp/golang/bootcamp-golang-studidevsecops/sesi-16/devstore/db

  migrate:
    image: migrate/migrate:v4.15.2
    profiles: ["tools"]
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@db:5432/devstoredb_development?sslmode=disable",
      ]
    command: ["up"]
    depends_on:
      db:
        condition: service_healthy
  

volumes:
  postgres_data:

  